version: "3.8"

services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    # Or specify a version tag if needed
    container_name: mediamtx
    ports:
      - "8554:8554"   # RTSP
      - "1935:1935"   # RTMP
      - "8888:8888"   # HLS
    # (MediaMTX also has webRTC and SRT ports if you need them)
    restart: always

  rtsp-streamer:
    build: ./rtsp-streamer
    container_name: rtsp-streamer
    depends_on:
      - mediamtx
    volumes:
      - ./assets/mock-videos:/videos
    environment:
      - VIDEO_FILE=video2.mp4
      - STREAM_PATH=mystream2
    restart: always
