version: "3.8"
services:
  rtsp-server:
    image: aler9/rtsp-simple-server
    ports:
      - "8554:8554"
    networks:
      - rtsp-net

  rtsp-streamer2:
    build: ./rtsp-streamer
    depends_on:
      - rtsp-server
    volumes:
      - ./assets/mock-videos:/videos
    environment:
      - VIDEO_FILE=video2.mp4
      - STREAM_PATH=mystream2
    networks:
      - rtsp-net
    restart: always

networks:
  rtsp-net:
    driver: bridge
