version: "3.8"

services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    ports:
      - "8554:8554"    # RTSP
      # Additional ports if you need RTMP, HLS, WebRTC, etc.
    restart: always

  # The container that streams 3 videos
  rtsp-streamer:
    build: ./rtsp-streamer
    container_name: rtsp-streamer
    depends_on:
      - mediamtx
    volumes:
      - ./assets/mock-videos:/videos
    environment:
      - VIDEO_FILE_1=video1.mp4
      - VIDEO_FILE_2=video2.mp4
      - VIDEO_FILE_3=video3.mp4
      - STREAM_PATH_1=stream1
      - STREAM_PATH_2=stream2
      - STREAM_PATH_3=stream3
    restart: always